# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - echo "Everything is awesome!"
  branches:
    master:
      - step:
          name: Deploy
          script:
            - git config --global user.email "info@vektor-inc.co.jp"
            - git config --global user.name "bitbucket-piplines-vk-blocks-pro"
            - git clone git@github.com:vektor-inc/vk-blocks.git
            - rsync  --exclude 'src/outer' --exclude 'src/timeline-item' --exclude 'src/timeline' --exclude 'src/table-of-contents' --exclude 'src/post-list' --exclude 'src/step' --exclude 'src/step-item' --exclude 'vk-blocks/' --exclude '.node-version' --exclude 'bin/' --exclude '.git/' --exclude '.gitignore' --exclude '.circleci/' --exclude 'tests/' --exclude '.phpcs.xml.dist' --exclude 'bitbucket-pipelines.yml' --exclude 'package-lock.json' --exclude 'phpunit.xml' --exclude 'phpunit.xml.dist' --exclude 'inc/plugin-update-checker/' --exclude 'inc/vk-blocks/build/*.css' --exclude 'inc/vk-blocks/build/*.js' --exclude 'editor-css/*.scss' --exclude 'editor-css/*.css' --exclude 'editor-css/*.css.map' -avc ./* ./vk-blocks
            - cd ./vk-blocks/
            - git checkout -b add/example
            - git rm -r tests/
            - git rm -r bin/
            - git rm inc/vk-blocks/build/block-build.css
            - git rm src/table-of-contents
            - git rm src/outer
            - git add .
            - git status
            - git commit -m"Update from vk-blocks-pro"
            - git push -f origin add/example
