export default [
	//Free
	{ label: "Alert", slug: "vk-blocks/alert" },
	{ label: "Ballon", slug: "vk-blocks/balloon" },
	{ label: "Border Box", slug: "vk-blocks/border-box" },
	{ label: "Button", slug: "vk-blocks/button", index: 1  },
	{ label: "Classic FAQ", slug: "vk-blocks/faq" },
	{ label: "New FAQ", slug: "vk-blocks/faq2" },
	{ label: "Flow", slug: "vk-blocks/flow" },
	{ label: "Heading", slug: "vk-blocks/heading", index: 1  },
	{ label: "PR Blocks", slug: "vk-blocks/pr-blocks" },
	{ label: "PR Content", slug: "vk-blocks/pr-content" },
	{ label: "Responsive Spacer", slug: "vk-blocks/spacer" },
	{ label: "Staff", slug: "vk-blocks/staff" },
	// Pro
	{ label: "Animation", slug: "vk-blocks/animation" },
	{ label: "Card", slug: "vk-blocks/card", index: 1 },
	{ label: "Child page list", slug: "vk-blocks/child-page" },
	{ label: "Grid Column", slug: "vk-blocks/grid-column" },
	{ label: "Icon Card", slug: "vk-blocks/icon-card" },
	{ label: "Outer", slug: "vk-blocks/outer" },
	{ label: "Post list", slug: "vk-blocks/post-list" },
	{ label: "Slider", slug: "vk-blocks/slider" },
	{ label: "Step", slug: "vk-blocks/step" },
	{ label: "Table of Contents", slug: "vk-blocks/table-of-contents-new" },
	{ label: "Timeline", slug: "vk-blocks/timeline" },
];
