# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deprecated Test and Lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  plugin_name: vk-blocks-pro

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install NPM Scripts
      run: npm install
    - name: Install Composer Package ( no-dev )
      run: composer install --no-dev
    - name: Install @wordpress/env
      run: npm install -g @wordpress/env
    - name: Run @wordpress/env
      run: |
        n=0
        until [ "$n" -ge 3 ]
        do
          npx wp-env start && break
          n=$((n+1))
          echo "Retrying wp-env start ($n)..."
          sleep 5
        done
    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mv wp-cli.phar /usr/local/bin/wp
    - name: Build
      run: npm run build

    # 各ブロックのlintを実行
    - name: Run lint.
      run: |
        npm run lint
    
    # 後方互換テスト実行
    - name: Run deprecated test.
      run: |
        npm run test-unit