# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deprecated Test and Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  plugin_name: vk-blocks-pro

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # get the node version from the .node-version file
    - name: Read .node-version
      run: echo "##[set-output name=NODEVERSION;]$(cat .node-version)"
      id: nodenv

    # setup node based on the version from the .node-version file, fetched in the previous step
    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nodenv.outputs.NODEVERSION }}"

    - name: Build
      run: |
        npm install
        npm run build

    # 各ブロックのlintを実行
    - name: Run lint.
      run: |
        npm run lint
    
    # 後方互換テスト実行
    - name: Run deprecated test.
      run: |
        npm run test-unit