# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to VK Blocks Free

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
env:
  plugin_name: vk-blocks-pro
  GIT_TOKEN: ${{ secrets.ACCESSTOKEN_FOR_VK_BLOCKS_FREE }}
  GIT_USER: ${{ secrets.GIT_USER }}
  GIT_REPOSITORY: ${{ secrets.GIT_REPOSITORY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    # 通常版をクローン Tagのバージョンを取得。
    # GITHUB_REFには、refs/tags/0.0.0 が値が入っているので前から10文字を削除して、バージョンのみを取得する。
    # https://qiita.com/maruware/items/3da1f5866f6f233a1ad1#%E3%82%BF%E3%82%B0%E5%90%8D%E3%82%92%E5%A4%89%E6%95%B0%E3%81%A8%E3%81%97%E3%81%A6%E4%BD%BF%E7%94%A8
    - name: Get tag version
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    # https://qiita.com/shonansurvivors/items/f256a0443d346f09448e
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g npm
    # 通常版をクローン
    - run: git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}
    # VK BlocksのGithubにアクセスできるユーザーの設定
    - run: git config --global user.email "info@vektor-inc.co.jp"
    - run: git config --global user.name "bitbucket-piplines-vk-blocks-pro"
    # 無料版にデプロイするスクリプトにタグ名を引数で渡す。
    - run: bash bin/deploy-free.sh $RELEASE_VERSION