# Deploy develop branch to vs4 test

name: Deploy to VK Blocks Pro Test Site
on:
  push:
    branches:
      - develop
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # get the node version from the .node-version file
      - name: Read .node-version
        run: echo "##[set-output name=NODEVERSION;]$(cat .node-version)"
        id: nodenv
      # setup node based on the version from the .node-version file, fetched in the previous step
      - name: Setup Node.js (.node-version)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nodenv.outputs.NODEVERSION }}"

      - name: Setup Enviroment
        run: npm install
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
      - name: build
        run: npm run build
      - name: dist
        run: npm run dist

      - name: Deploy to test server [ Deprecated ]
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: /dist/vk-blocks-pro/
          remote_path: /home/vs4/www/vk-block-test/wp-content/plugins/vk-blocks-pro/
          remote_host: ${{ secrets.DEPLOY_HOST_VS4 }}
          remote_port: ${{ secrets.DEPLOY_PORT_VS4 }}
          remote_user: ${{ secrets.DEPLOY_USER_VS4 }}
          remote_key: ${{ secrets.DEPLOY_KEY_VS4 }}
