# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to VK Blocks Free

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
env:
  plugin_name: vk-blocks-pro
  GIT_TOKEN: ${{ secrets.ACCESSTOKEN_FOR_VK_BLOCKS_FREE }}
  GIT_USER: ${{ secrets.GIT_USER }}
  GIT_REPOSITORY: ${{ secrets.GIT_REPOSITORY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npx gulp dist
    - run: cd dist/ && zip -r ${{ env.plugin_name }}.zip ${{ env.plugin_name }}/ && mv ${{ env.plugin_name }}.zip ${GITHUB_WORKSPACE}
    
    - run: npm install -g npm
    # VK BlocksのGithubにアクセスできるユーザーの設定
    - run: git config --global user.email "info@vektor-inc.co.jp"
    - run: git config --global user.name "bitbucket-piplines-vk-blocks-pro"
    # 通常版をクローン
    - run: git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}
    - run: mv vk-blocks/ vk-blocks-free/
    
    - run: cd vk-blocks-free
    - run: rm -rf src/*
    - run: cd ../
    # 指定したファイルを除外して、Pro版をコピー&上書き
    - run: rsync --exclude 'inc/vk-blocks/build/block-build.css' --exclude 'src/outer/' --exclude 'src/table-of-contents/' --exclude 'bin/' --exclude 'tests/' --exclude 'inc/vk-blocks-pro-config.php' --exclude 'src/blocks/_pro/' --exclude 'vk-blocks-free/' --exclude '.node-version' --exclude 'bin/' --exclude '.git/' --exclude '.gitignore' --exclude '.circleci/' --exclude 'tests/' --exclude '.phpcs.xml.dist' --exclude 'bitbucket-pipelines.yml' --exclude 'package-lock.json' --exclude 'phpunit.xml' --exclude 'phpunit.xml.dist' --exclude 'inc/plugin-update-checker/' --exclude 'inc/vk-blocks/build/*.css' --exclude 'inc/vk-blocks/build/*.js' --exclude 'editor-css/*.css' --exclude 'editor-css/*.css.map' -arvc ./* ./vk-blocks-free/
    - run: cd ./vk-blocks-free/
    # push先のブランチを切る
    - run: git checkout -b add/vk-blocks-free
    - run: ls
    - run: cd src
    - run: ls
    - run: cd src/blocks/
    - run: ls
    # Pro版ブロックは読み込まないようjsから削除
    - run: sed -i /_pro/d src/blocks/bundle.js
    # プラグイン名を通常版へリネーム
    - run: sed -i 3s/Pro// vk-blocks.php
    # Pro版のブロックslugを配列に追加（後で使用する）
    - run: cd ../
    - run: pro_block_array=($(ls src/blocks/_pro/))
    - run: cd ./vk-blocks-free/
    # Pro版のブロックをphpから削除
    - run: for pro_block in ${pro_block_array[@]}; do
    - run: sed -i s/\,\ \'${pro_block}\'//g inc/vk-blocks/vk-blocks-functions.php
    - run: done
    # ブロックをビルド
    - run: npm install
    - run: npm run build
    # 以下はadd/vk-blocks-freeブランチにpushするための処理
    - run: git add .
    - run: git commit -m"Update from vk-blocks-pro"
    - run: git push -f origin add/vk-blocks-free
