name: E2E Test | Deprecated

on:
  push:
    branches:
      - feature/e2e-test-by-wp-scripts
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        block-version: [0.55.0, 0.54.2]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      # run the wp-env setup command (wp-env start)
      - name: setup wp env
        run: |
          npx wp-env start

      - name: prepare for test.
        run: |
          mv tests/ ../tests/

      - name: checkout ${{ matrix.block-version }}
        run: |
          git pull --tags
          git checkout -f refs/tags/${{ matrix.block-version }}
          npm run build

      - name: prepare for test.
        run: |
          mv ../tests/ ./tests/

      - name: Insert Blocks
        run: |
          npx wp-scripts test-e2e tests/e2e/blocks/all/block-is-not-broken.spec.js

      - name: Checkout current branch
        run: |
          git checkout -f ${{github.head_ref}}
          npm run build

      - name: Deprecated test
        run: |
          npx wp-scripts test-e2e tests/e2e/blocks/all/deprecated.spec.js