# This is a basic workflow to help you get started with Actions

name: E2E Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ fix/remove-hidden-setting-from-grid-column-item ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # get the node version from the .node-version file
      - name: Read .node-version
        run: echo "##[set-output name=NODEVERSION;]$(cat .node-version)"
        id: nodenv

      # setup node based on the version from the .node-version file, fetched in the previous step
      - name: Setup Node.js (.node-version)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nodenv.outputs.NODEVERSION }}"

      # run npm install
      - name: npm install
        run: |
          npm install

      # run the wp-env setup command (wp-env start)
      - name: setup wp env
        run: |
          npx wp-env start

      # run E2E test (Cypress)
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true