name: Playwright Tests
on:
  pull_request:
    branches: [ develop ]
jobs:
    e2e-playwright:
        timeout-minutes: 60
        name: Playwright
        runs-on: ubuntu-latest
        strategy:
          matrix:
            php: [8.1]
        steps:
            - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                path: vendor
                key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14.x
            - name: Install WP-CLI
              run: |
                curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                chmod +x wp-cli.phar
                mv wp-cli.phar /usr/local/bin/wp
            - name: install npm scripts
              run: npm install
            - name: install Composer Package
              run: composer install
            - name: Npm build
              run: npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start
            - name: Run Playwright
              run: npx playwright test --trace on --project=chromium
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
