name: Playwright Tests
on:
  pull_request:
    branches: [develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install npm scripts
        run: npm install
      - name: install Composer Package
        run: composer install
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
      - name: Build
        run: npm run build
      - name: Run Environment
        run: npx wp-env start
      - name: Create Upgrade Directory
        run: |
          sudo mkdir -p /var/www/html/wp-content/upgrade
          sudo chown -R www-data:www-data /var/www/html/wp-content/upgrade
          sudo chmod -R 755 /var/www/html/wp-content/upgrade
      - name: Install Plugin using WP-CLI
        run: |
          npx wp plugin install vk-all-in-one-expansion-unit --activate
      - name: Run Playwright
        run: npx playwright test --trace on --project=chromium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
